### ISSUE TITLE
No current location update...

### ISSUE THREAD

**Issue by Rubiromi** [soolaimon/mobile_noms#10]
After I set my current location (not truck current location, but where the user is), there is no ways to update current location, or set the location user would like to use.
i.g. if user is taking trips or something and checking noms trucks around somewhere he is currently not at...

**Comment by soolaimon** [comment]
Hmm... on mine it updates the location every time I go to the home page (which is actually kind of annoying because it asks every time- I was trying to find a way to fix that). But ideally we'd have a button they can just tap/click that updates the current location whenever they want. Let's do that. 

I need to clean up and organize the javascript code to make it less of a pain to implement.
